# Definimos el tipo de dB
quarkus.datasource.db-kind=postgresql

# Usuario y contraseña con el que se conecta a la dB
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
 
# URL de conexión a la dB
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2t

# CAMBIO AQUÍ: Ahora actualiza la estructura sin borrar los datos acumulados
 quarkus.hibernate-orm.database.generation=drop-and-create
# Sincroniza el código a la dB sin borrar los datos existentes
# quarkus.hibernate-orm.database.generation=update

# Comentamos el import para que no intente insertar duplicados en cada reinicio
# quarkus.hibernate-orm.sql-load-script=import.sql

# Muestra en la consola el SQL
quarkus.hibernate-orm.log.sql=true